name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: |
          npm install
          npm install --prefix server

      # 4️⃣ Build frontend
      - name: Build frontend
        run: npm run build

      # 5️⃣ Configurer SSH pour Ansible
      - name: Configure SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          ssh-keyscan -H 217.182.66.173 >> $HOME/.ssh/known_hosts

      # 6️⃣ Installer Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # 7️⃣ Déployer avec Ansible
      - name: Deploy with Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
            -e "frontend_build_src=${{ github.workspace }}/client/dist"
